"""
Export references_corpus.bib with PDF-first URLs where possible.

Usage (from project root):
  python utils/export_corpus_bib.py
  python utils/export_corpus_bib.py --out references_corpus.bib

Rules:
  - uk_statutory: legislation.gov.uk /pdfs/ URL when derivable from source_url
  - international_precedent (World Bank): WDS pdfurl when API returns it; else source page
  - uk_guidance: gov.uk page URL; if docs/pdfs/{corpus}/{stem}.pdf exists, note archived PDF
  - Local CSVs: project dataset entries (no PDF)
"""
from __future__ import annotations

import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "modules"))

import config
import pdf_store

CORPORA = ["uk_statutory", "uk_guidance", "international_precedent"]
WDS_API = "https://search.worldbank.org/api/v2/wds"


def _slug_key(stem: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", stem).strip("_").lower()
    return f"ragcorpus_{s[:55]}"


def _year(published: str) -> str:
    if published and len(published) >= 4:
        return published[:4]
    return "n.d."


def _legislation_pdf_url(source_url: str) -> str | None:
    """Map legislation.gov.uk data.xml URL to official /pdfs/ link."""
    m = re.search(
        r"legislation\.gov\.uk/(ukpga|eur)/(\d{4})/(\d+)",
        source_url,
        re.I,
    )
    if not m:
        return None
    kind, year, num = m.group(1).lower(), m.group(2), m.group(3)
    if kind == "ukpga":
        code = f"ukpga_{year}{int(num):04d}_en.pdf"
    else:
        code = f"eur_{year}{int(num):04d}_en.pdf"
    return f"https://www.legislation.gov.uk/{kind}/{year}/{num}/pdfs/{code}"


def _worldbank_pdfurl(page_url: str) -> str | None:
    m = re.search(r"/curated/en/(\d+)", page_url)
    if not m:
        return None
    doc_id = m.group(1)
    q = urllib.parse.urlencode(
        {"format": "json", "qterm": doc_id, "rows": 3, "fl": "pdfurl,url"}
    )
    try:
        with urllib.request.urlopen(f"{WDS_API}?{q}", timeout=20) as resp:
            data = json.loads(resp.read().decode())
        for doc in data.get("documents", {}).get("doc", []) or []:
            pdfurl = doc.get("pdfurl")
            if pdfurl:
                return pdfurl
    except Exception:
        pass
    return None


def _bib_entry(
    key: str,
    entry_type: str,
    author: str,
    title: str,
    year: str,
    url: str | None,
    note: str,
) -> str:
    lines = [f"@{entry_type}{{{key},"]
    lines.append(f"  author = {{{author}}},")
    lines.append(f"  title = {{{title}}},")
    lines.append(f"  year = {{{year}}},")
    if url:
        lines.append(f"  url = {{{url}}},")
        lines.append(f"  urldate = {{2026-08-26}},")
    lines.append(f"  note = {{{note}}},")
    lines.append("}")
    return "\n".join(lines)


def _export() -> str:
    blocks = [
        "% Auto-generated by utils/export_corpus_bib.py — cite PDF/url in `url` field.",
        "",
        _bib_entry(
            "swindon_rag_verified_corpus_2026",
            "misc",
            "{Swindon GVA RAG Project}",
            "Verified Policy Evidence Corpus for Swindon {GVA} {RAG} Pilot",
            "2026",
            None,
            "34 policy documents + 2 local-evidence tables. Authoritative PDFs or source pages in individual entries below.",
        ),
        "",
    ]

    for corpus in CORPORA:
        blocks.append(f"% --- {corpus} ---")
        for meta_path in sorted((config.DATA_VERIFIED / corpus).glob("*.meta.json")):
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            stem = meta_path.name.replace(".meta.json", "")
            txt_path = meta_path.with_suffix(".txt")
            title = (meta.get("title") or stem.replace("_", " ")).strip().replace("\n", " ")
            author = meta.get("issuing_authority") or "Unknown"
            year = _year(meta.get("published_date") or "")
            source_url = meta.get("source_url") or ""
            key = _slug_key(stem)

            pdf_path = pdf_store.resolve_pdf_path(corpus, txt_path) if txt_path.exists() else None
            archived = pdf_path.as_posix() if pdf_path else None

            url: str | None = None
            note_parts = [f"RAG corpus tier: \\textit{{{corpus.replace('_', '\\_')}}}."]

            if corpus == "uk_statutory":
                entry_type = "misc"
                url = _legislation_pdf_url(source_url) or source_url
                note_parts.append("Authoritative PDF on legislation.gov.uk when url ends with .pdf.")
            elif corpus == "international_precedent":
                entry_type = "report"
                url = _worldbank_pdfurl(source_url) or source_url
                note_parts.append("World Bank document; url prefers direct PDF when WDS returns pdfurl.")
            else:
                entry_type = "online"
                url = source_url or None
                if meta.get("has_raw_pdf") or archived:
                    note_parts.append("Project archived PDF available under docs/pdfs/.")
                else:
                    note_parts.append("GOV.UK HTML guidance; no standalone PDF at source.")

            if archived:
                note_parts.append(f"Archived copy: \\texttt{{{archived}}}.")

            blocks.append(
                _bib_entry(
                    key,
                    entry_type,
                    "{" + author + "}",
                    title.replace("&", "\\&"),
                    year,
                    url,
                    " ".join(note_parts),
                )
            )
            blocks.append("")

    for name, desc in (
        ("ragcorpus_ipi_tabpfn_2026", "Swindon LSOA IPI and bottleneck table (ipi_tabpfn.csv)"),
        ("ragcorpus_cluster_result_2026", "Swindon LSOA cluster typology table (cluster_result.csv)"),
    ):
        blocks.append(
            _bib_entry(
                name,
                "misc",
                "{Swindon GVA RAG Project}",
                desc,
                "2026",
                None,
                "Local-evidence tier; project-generated CSV, not an external PDF.",
            )
        )
        blocks.append("")

    return "\n".join(blocks)


def main() -> None:
    out = ROOT / "references_corpus.bib"
    if len(sys.argv) > 2 and sys.argv[1] == "--out":
        out = Path(sys.argv[2])
    text = _export()
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
